FROM centos:7
MAINTAINER jmrodri

ARG VERSION=master
ARG DEBUG_PORT=9000
LABEL "com.redhat.version"=$VERSION

ENV USER_NAME=pinger \
    USER_UID=1001 \
    BASE_DIR=/opt/pinger \
    DEBUG_PORT=${DEBUG_PORT}
ENV HOME=${BASE_DIR}

RUN mkdir -p ${BASE_DIR} ${BASE_DIR}/etc \
 && useradd -u ${USER_UID} -r -g 0 -M -d ${BASE_DIR} -b ${BASE_DIR} -s /sbin/nologin -c "pinger user" ${USER_NAME} \
 && chown -R ${USER_NAME}:0 ${BASE_DIR} \
 && chmod -R g+rw ${BASE_DIR} /etc/passwd


RUN yum -y update \
 && yum -y install epel-release centos-release-openshift-origin \
 && yum -y install net-tools bind-utils iputils \
 && yum clean all

WORKDIR ${HOME}

######################
# BUILD BROKER SOURCE
######################

COPY entrypoint.sh fetcher.sh /usr/bin/

USER ${USER_UID}
RUN sed "s@${USER_NAME}:x:${USER_UID}:@${USER_NAME}:x:\${USER_ID}:@g" /etc/passwd > ${BASE_DIR}/etc/passwd.template

ENTRYPOINT ["entrypoint.sh"]
